#include "plugin_manager.h"
#include <string.h>

#ifdef ZC_STATIC_PLUGINS
/* This file is normally generated by the Makefile for APE builds.
   If you are seeing this, it means you are building without the automatic
   plugin discovery or using a different build system. */
ZPlugin *zptr_get_static_plugin(const char *name)
{
    (void)name;
    return NULL;
}
#else
ZPlugin *zptr_get_static_plugin(const char *name)
{
    (void)name;
    return NULL;
}
#endif
